springContextFileLocation: spring.xml
version: ${project.version} (${buildNumber})

# ActiveMQ broker url
messaging:
    dataFormat: defaultDataFormat
    txnManager: camelRequiredTxn
    routing:
        numThreads: 10
    broker:
        url: tcp://localhost:61616
    events:
        repo:
            node:
                sourceTopic:
                    endpoint: amqp:topic:alfresco.events.repo.ext.nodes
#amqp:topic:alfresco.repo.events.nodes
    clientId: entities1
    durableSubscriptionName: entities

# Mongo persistence config
mongo:
    dbName: alfresco
    mongoURI: mongodb://127.0.0.1:27017

encryption:
    ssl:
        keystore:
            location: classpath:ssl.repo.client.keystore
            type: JCEKS
#            provider: "null"
            keyMetaData:
                location: classpath:ssl-keystore-passwords.properties

        truststore:
            location: classpath:ssl.repo.client.truststore
            type: JCEKS
#            provider: "null"
            keyMetaData:
                location: classpath:ssl-truststore-passwords.properties

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 9292

logging:
  level: INFO
  loggers:
    "org.alfresco.entities": DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      threshold: ALL
      currentLogFilename: ./logs/service-entities.log
      archive: true
      archivedLogFilenamePattern: ./logs/service-entities-%d.log.gz
      archivedFileCount: 5
